# Build configuration for tom_dist_ledger
#
# D4rt bridge configuration for DartScript integration.

targets:
  $default:
    builders:
      tom_d4rt_generator:d4rt_bridge_builder:
        enabled: true
        options:
          name: tom_dist_ledger
          modules:
            - name: all
              barrelFiles:
                - lib/tom_dist_ledger.dart
              outputPath: lib/src/d4rt_bridges/tom_dist_ledger_bridges.dart
              barrelImport: tom_dist_ledger.dart
              excludePatterns:
                - _bridge.dart
                - _generated.dart
              excludeClasses:
                - LedgerServer
                - RemoteLedgerClient
          helpersImport: package:tom_d4rt/tom_d4rt.dart
          generateBarrel: true
          barrelPath: lib/d4rt_bridges.dart
          generateDartscript: true
          dartscriptPath: lib/dartscript.dart
          registrationClass: TomDistLedgerBridges
